name: Build And Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Spotify.sln